#!/bin/sh -e

mkdir -p .build
cd .build
# Work around for LTO not being able to find the assets
if [ ! -L assets ]
then
	ln -s ../heditor/assets assets
fi

BUILD_TYPE=${1:-RelWithDebInfo}

cmake \
    -G "Ninja" \
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
    -DCMAKE_TOOLCHAIN_FILE=../cmake/linux.cmake ..
cmake --build .
